project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    background: danger
    left:
      - href: index.qmd
        text: Home
      - href: labs/index.qmd
        text: Labs
      - href: blog.qmd
        text: Blog

format:
  html:
    theme:
      - yeti
    css: styles.css
    toc: true