project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    background: "#0b4f27"
    left:
      - text: Home
        href: index.qmd
      - text: Labs
        menu:
          - text: Overview
            href: labs/index.qmd
          - text: Lab 1
            href: labs/lab-1/index.qmd
          - text: Lab 2
            href: labs/lab-2/index.qmd
      - text: Blog
        href: blog.qmd

format:
  html:
    theme:
      - cosmo
      - theme.scss
    toc: true
    toc-depth: 4